# Generated by Django 5.2.5 on 2025-08-22 06:08

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_tags_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdefgh12345', editable=False, length=10, max_length=20, prefix='cat', unique=True),
        ),
    ]
