# Generated by Django 5.2.5 on 2025-08-24 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='life',
            field=models.CharField(default='100 days', max_length=155),
        ),
        migrations.AddField(
            model_name='product',
            name='mfd',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='stock_count',
            field=models.CharField(default='10', max_length=155),
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(default='Type-1', max_length=155),
        ),
    ]
