# Generated by Django 5.2.5 on 2025-09-02 09:44

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='order_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=12, max_length=20, prefix='ord', unique=True),
        ),
    ]
