# Generated by Django 5.2.5 on 2025-09-02 09:49

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cartorder_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorder',
            name='order_id',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='1234567890', length=12, max_length=20, prefix='slrs', unique=True),
        ),
    ]
