# Generated by Django 5.2.5 on 2025-09-02 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_cartorder_fraud_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='fraud_status',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='midtrans_transaction_id',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='cartorder',
            name='transaction_status',
        ),
    ]
