# Generated by Django 5.2.5 on 2025-09-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_cartorder_fraud_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='fraud_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='midtrans_transaction_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='transaction_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cartorder',
            name='product_status',
            field=models.CharField(choices=[('processing', 'Processing'), ('shiped', 'Shiped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='processing', max_length=35),
        ),
    ]
