# Generated by Django 5.2.5 on 2025-09-02 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_cartorder_fraud_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorderitems',
            name='invoice_no',
        ),
        migrations.RemoveField(
            model_name='cartorderitems',
            name='product_status',
        ),
    ]
